disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Works without WiFi"
baseURL = "https://workswithoutwifi.com/"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Explore offline-ready tech for parenting, privacy, minimalism, and off-grid living."
logo = "img/logo.png"
defaultBackgroundImage = "/img/background.svg"
