name: Deploy Site to Hostinger

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v3
              with:
                  hugo-version: 'latest' # replace with your Hugo version

            - name: Build Site
              run: hugo

            - name: Deploy to Hostinger via rsync over SSH
              uses: burnett01/rsync-deployments@7.0.2
              with:
                  switches: -avz --delete
                  path: public/
                  remote_port: 65002
                  remote_path: ${{ secrets.DEPLOY_PATH }}
                  remote_host: ${{ secrets.HOSTINGER_HOST }}
                  remote_user: ${{ secrets.HOSTINGER_USER }}
                  remote_key: ${{ secrets.HOSTINGER_KEY }}
